spring.application.name=JDBCEg


#specify properties the application loads the configuration is there and
#properties set and it can be used
#default userName is postgres
#only only one colon after jdbc unlike before configuration in learning
spring.datasource.url=jdbc:postgresql://localhost:5433/DemoRepoService
spring.datasource.username= postgres
spring.datasource.password=0626
spring.datasource.driver-class-name=org.postgresql.Driver